### PR TITLE
Ticked version, regenerated if needed. (Double-check reqs!)

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by kwilcox** [comment]
I don't see the ticked version?

**Comment by pmlandwehr** [comment]
Yeah, this run of my script was bugged. I'm not sure what went wrong, but something needs debugging. Meanwhile, I'll be upgrading this by hand.

**Comment by pmlandwehr** [comment]
Ok - this should run. Let me note as an aside that celery has a *lot* of optional run reqs that we could be including here. My assumption is that we should omit them so that we don't include a lot of potentially unnecessary drivers, but on other projects I've gone the opposite direction as being more appropriate for conda.

**Comment by kwilcox** [comment]
I'm in the "include everything" camp but lost that battle regarding the inclusion of `gdal` in the `django` dependencies.

We could create meta packages `celery[redis]`, `celery[amqp]`, etc. to stay consistent with the packages available in PyPI

**Comment by kwilcox** [comment]
Why `pytz >dev`?

**Comment by pmlandwehr** [comment]
Got it from the default requirements here: https://github.com/celery/celery/blob/master/requirements/default.txt#L1

**Comment by pmlandwehr** [comment]
Closing this up for now, will resolve later.

**Pull request closed without merging**
