### PR TITLE
Update dep versions

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
The main issue was the outdated `click` version constraint.

**Comment by mcs07** [comment]
The relevant upstream PR is here: https://github.com/celery/celery/pull/6861

It has been merged but not yet released, so this change is not suitable for the current 5.1.2 version. We'll have to wait until it is released (seems like it is in the 5.2 milestone)

**Comment by hadim** [comment]
My bad, I was looking on `master` only.

**Comment by hadim** [comment]
I let this open as a reminder to bump the deps when 5.2 is released.

**Comment by pedrosanta** [comment]
@hadim 5.2 and 5.2.1 has since been released, and the builds for these versions on conda-forge seem to be failing (#56 and #57). You mentioned you wanted this bumped when 5.2 was released, I wonder if this work will fix those PRs/builds too.

Cheers.

**Comment by pedrosanta** [comment]
I've looked into the files changed, and it really seems to me that releasing/merging this will fix the #56 and #57 PRs.

Will stand by on this then.

**Comment by hadim** [comment]
I don't have time to care of this at the moment. You could open a PR based on this one and using the 5.2.1 tag. The only thing would be to sync the dep using upstream at https://github.com/celery/celery/blob/v5.2.1/requirements/default.txt

**Comment by mcs07** [comment]
Superseded by #58

**Pull request closed without merging**
