### PR TITLE
celery v5.2.1

### PR DESCRIPTION
**Pull request by pedrosanta**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Following up on #55.

### CODE REVIEW

**Comment by pedrosanta** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
Looks like the error is due to kombu. The PR for that version is green at https://github.com/conda-forge/kombu-feedstock/pull/51 so you should ping the folks there to merge it.

**Comment by hadim** [comment]
kombu has been merged. You could restart  the CI here and see if it fixes it.

**Comment by MichelML** [comment]
repoke @chrisburr @igortg @kwilcox @mcs07 @sodre if this has been forgotten

**Comment by mcs07** [comment]
@conda-forge-admin, please restart ci

**Comment by mcs07** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
