### PR TITLE
Update v5.3.5

### PR DESCRIPTION
**Pull request by rxm7706**
fix kombu version, remove pytz
rerendered using grayskull

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

this will fail till the pending pr is merged and available for use
- https://github.com/conda-forge/amqp-feedstock/pull/40

closes https://github.com/conda-forge/celery-feedstock/pull/86
closes https://github.com/conda-forge/celery-feedstock/pull/87

tested locally, with a version of amqp built to support vine >=5.0,<6.0 - all tests pass - with some warnings
`================ 157 passed, 11 skipped, 29 warnings in 17.22s =================`

Next Version Upgrade
https://github.com/rxm7706/celery-feedstock/blob/v5.3.6/recipe/meta.yaml

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please restart ci

**Comment by rxm7706** [comment]
@efiop @sodre @kwilcox @chrisburr 
This is ready for your review and merge. Description contains details ! Thanks and Regards

**Review by efiop — APPROVED** [review]

**Comment by efiop** [comment]
Thank you @rxm7706 !

**Pull request merged**
