### PR TITLE
Update template, tick version to 3.1.25, rerender

### PR DESCRIPTION
**Pull request by pmlandwehr**
Wanted to get some `py36` builds, so did a rerender. Also tweaked the template to get in license info, sha256, and added myself as a maintainer, and took the version up to the last `3.1.x` release. (There are now some `4.0.x` releases, but should probably finish this series first.)

### CODE REVIEW

**Comment by pmlandwehr** [comment]
hmmm - seems like I didn't get my desired `py36` builds. Must need to fix some other dependencies.

**Comment by pmlandwehr** [comment]
Hmm - seems like we could remove the `kombu` build req if we update the conda-forge feedstock a little bit.

**Comment by pmlandwehr** [comment]
I seem to be getting a build failure here when testing either `celery -h` (which appears to exit correctly) or `celeryd -h` (which doesn't appear to start). If anyone in @conda-forge/celery has an idea I'd be glad to hear it.

**Comment by kwilcox** [comment]
With version `3.1.23`, `celery --help` return an exit code of 1, so we shouldn't use that as a test at all.

The other three commands have been deprecated and we are better off testing that these return 0:

```
celery --version
celery worker --help
celery beat --help
celery multi --help
celery shell --help
```

**Comment by pmlandwehr** [comment]
The build dies after `celery multi --help`. Would anything be up with `celery shell`?

**Comment by kwilcox** [comment]
Looks like the multi help command is actually `celery multi help`, contrary to all other celery subcommands.

**Comment by kwilcox** [comment]
Thanks for the persistence!

**Pull request merged**
