### PR TITLE
Add cryptography to meta.yaml

### PR DESCRIPTION
**Pull request by edetec**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by edetec** [comment]
@conda-forge-admin, please re-render.

**Comment by edetec** [comment]
@conda-forge-admin, please rerender

**Comment by igortg** [comment]
@conda-forge-admin, please rerender

**Comment by edetec** [comment]
@conda-forge-admin, please update team

**Pull request closed without merging**
