### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by edetec**
Fixing dependencies error.

### CODE REVIEW

**Comment by edetec** [comment]
@conda-forge/core, can we merge it?

**Comment by ocefpaf** [comment]
@edetec consider adding yourself as a maintainer here so you can merge PRs like this one.

**Comment by edetec** [comment]
I have requested https://github.com/conda-forge/celery-feedstock/pull/27

**Comment by ocefpaf** [comment]
> I have requested #27 @ocefpaf

Great! You should be added as a maintainer here soon then.

**Comment by edetec** [comment]
> > I have requested #27 @ocefpaf
> 
> Great! You should be added as a maintainer here soon then.

Okay, thanks.

**Pull request merged**
